//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace com.mob.mobpush{
	/// <summary>
	/// Response state.
	/// </summary>
	public class ResponseState
	{
		public static int CoutomMessage = 0;		//CoutomMessage
		public static int MessageRecvice = 1;		//MessageRecvice
		public static int MessageOpened = 2;		//MessageOpened
	}

}

